##
# Grab first target
##
craft:
	@echo $(call craft.hello)


##
# Common variables 
#
include make/common.mk


##
# Common variables 
#
include make/lib/craft/craft.mk


##
# Common build interface targets
##
include make/lib/build/build.mk


##
# Common install interface targets
##
include make/lib/install/install.mk


##
# Common clean interface targets
##
include make/lib/clean/clean.mk


##
# Common tools interface targets
##
include make/lib/tools/tools.mk


##
# Common test interface targets
##
include make/lib/test/test.mk